from abc import ABC, abstractmethod
from typing import AsyncGenerator, List, Dict, Any
from app.providers.ai.models import ModelRequest, ModelResponse, ModelMetadata

class AIProvider(ABC):
    @abstractmethod
    def get_name(self) -> str:
        """Return the unique string name key of the provider (e.g. 'openai')."""
        pass

    @abstractmethod
    async def generate_completion(self, req: ModelRequest) -> ModelResponse:
        """Submit a complete chat execution and return the full text response."""
        pass

    @abstractmethod
    async def generate_stream(self, req: ModelRequest) -> AsyncGenerator[ModelResponse, None]:
        """Stream response completion chunks as they are generated by the model."""
        pass

    @abstractmethod
    async def get_models(self) -> List[ModelMetadata]:
        """Query provider registry and return lists of accessible active models."""
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """Verify network connectivity and authentication tokens against target host."""
        pass
