from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the message author (system, user, assistant)")
    content: str = Field(..., description="Content of the message text")

class ModelRequest(BaseModel):
    model: str = Field(..., description="String identifier of the target model")
    messages: List[ChatMessage] = Field(..., description="Context messages logs")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    max_tokens: Optional[int] = Field(default=None, ge=1)
    stream: bool = Field(default=False)
    extra_params: Dict[str, Any] = Field(default_factory=dict)

class TokenUsage(BaseModel):
    prompt_tokens: int = Field(default=0)
    completion_tokens: int = Field(default=0)
    total_tokens: int = Field(default=0)

class ModelResponse(BaseModel):
    content: str = Field(..., description="Result text generated by the model")
    model: str = Field(..., description="Name of the model that executed the prompt")
    usage: TokenUsage = Field(default_factory=TokenUsage)
    latency_ms: int = Field(..., description="Total processing time in milliseconds")
    finish_reason: Optional[str] = Field(default=None)
    cost_estimate: float = Field(default=0.0, description="Calculated query cost in USD")

class ModelMetadata(BaseModel):
    name: str
    context_length: int = 4096
    capabilities: List[str] = Field(default_factory=list)
    cost_per_1k_input: float = 0.0
    cost_per_1k_output: float = 0.0

class ProviderStatus(BaseModel):
    name: str
    is_active: bool
    latency_ms: int
    available_models: List[str]

class BenchmarkResult(BaseModel):
    provider: str
    model: str
    latency_ms: int
    tokens_per_second: float
    success: bool
    error_message: Optional[str] = None
